### PR TITLE
Fixed onMapReady event on iOS to resemble onMapReady on Android

### LINKED ISSUE #1605: Unable to scroll map on IOS
I have been trying to solve this issue where regardless of what i do, after refreshing the app. I am able to first pan when the screen is first loaded, after the map stops scrolling. I am unable to get it scrolling again. I am desperate for this to work and I have been trying for days without any solution to my problem. Hope someone can help me with this.

Upon further interaction, _specific behaviour is that after you double tap to zoom, you are able to scroll till you release. Then till you double tap to zoom again, you can't scroll._

If it helps, my project is currently using these versions:
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.3",
    "react-native-maps": "0.16.0",

**Update 01/09/17 **
Out of desperation to try anything, I upgraded to 
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.2",
    "react-native-maps": "0.16.2",

Also changed region props to initialRegion, then the issue seems to go away.

### LINKED ISSUE #1680: [iOS, Google Maps] Issues with  panning with controlled region
When trying to work around the issues with `initialRegion` outlined in #1613, I tried using the `MapView` `region` prop.

I've noticed that panning doesn't work. Sometimes the map ends up of moving but it's unpredictable and choppy. Is anyone else seeing these issue?

Removing either `provider={PROVIDER_GOOGLE}` or `region={this.state.region`} fixes the panning issue.

### LINKED ISSUE #1696: Mapview stuck cann't back and cann't zoom or change region
What's wrong ?

```
import React from 'react';
import {
  StyleSheet,
  View,
  Text,
  Dimensions,
  TouchableOpacity,
} from 'react-native';

import { Container, Button, Header, Title, Body, Left, 
     Right, Icon, Content, Form, Item, Input, Label } from "native-base";

import MapView from 'react-native-maps';
import CustomCallout from './CustomCallout';
import moment from 'moment';
import Spinner from 'react-native-loading-spinner-overlay';

const { width, height } = Dimensions.get('window');

const ASPECT_RATIO = width / height;
const LATITUDE = 3.594106;
const LONGITUDE = 98.672397;
const LATITUDE2 = 3.62598160;
const LONGITUDE2 = 98.66993210;
const LATITUDE_DELTA = 0.01995;
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;

const imagePin = require("../../../img/green-dot-20.png");

import globalStyle from "../../themes/GlobalStyle";


class LocationPolyline extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      region: {
        latitude: LATITUDE,
        longitude: LONGITUDE,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      },
      initialRegion: {
        latitude: LATITUDE,
        longitude: LONGITUDE,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      },
      marker1: null,
      marker2: null,
      desc: "",
      desc2: "",
      coordinates:[],
      showLoader: false,
      textLoader:"Retrieve Location"
    };
  }

  componentDidMount(){
      var data = this.props.navigation.state.params.data;
      var param = this.props.navigation.state.params.param;
      this.setState({showLoader: true, desc:data.StartRemarks ? data.StartRemarks: "", desc2:data.FinishRemarks ? data.FinishRemarks: ""});
      global.getTripHistory(param, (status, value) => {
        if(status){
          console.log('seharusnya bisa',value);
          var tmp = value[0] || [];
          var datas = tmp.Details.map(function(i){return {latitude: parseFloat(i.Lat), longitude: parseFloat(i.Lng), time: i.Time} });
          console.log(datas, datas.length);
          this.setState({showLoader: false, coordinates:datas});
          if(datas.length > 0){
            var marker1 = {latitude:datas[0].latitude,longitude:datas[0].longitude, latitudeDelta: LATITUDE_DELTA,longitudeDelta: LONGITUDE_DELTA};
            var marker2 = {latitude:datas[datas.length-1].latitude,longitude:datas[datas.length-1].longitude, latitudeDelta: LATITUDE_DELTA,longitudeDelta: LONGITUDE_DELTA};
            this.setState({marker1:marker1,marker2:marker2,region:marker1});
          }
          else{
            var marker1 = {latitude:parseFloat(value.StartLatitude),longitude:parseFloat(value.StartLongitude), latitudeDelta: LATITUDE_DELTA,longitudeDelta: LONGITUDE_DELTA};
            var marker2 = {latitude:parseFloat(value.FinishLatitude),longitude:parseFloat(value.FinishLongitude), latitudeDelta: LATITUDE_DELTA,longitudeDelta: LONGITUDE_DELTA};
          
            this.setState({marker1:marker1,marker2:marker2,region:marker1});
          }
        }
        else{
          this.setState({showLoader: false});
          console.log(status, value);
          global.commonAlert("Please check your connection", "Warning");
        }
      });
  }

  onRegionChange(region) {
    this.setState({ region });
  }

  render() {
      var titikTrip =  this.state.coordinates.map(function(data, index) {
        return <MapView.Marker
          coordinate={{latitude:data.latitude,longitude:data.longitude}}
          image={imagePin}
          title="Time"
          description={moment(data.time).format('HH:mm:ss')}
          key={index}
        />
      });
    return (
      <View style={styles.container}>
        <Header style={{backgroundColor:'#e67e22'}} androidStatusBarColor='#e67e22' >
          <Left>
            <Button transparent onPress={() => this.props.navigation.goBack()}>
              <Icon name="arrow-back" style={{paddingHorizontal: 10}}/>
            </Button>
          </Left>
          <Body>
            <Title>Location Trip</Title>
          </Body>
           <Right/>
        </Header>
        <MapView
          provider={this.props.provider}
          style={styles.map}
          initialRegion={this.state.initialRegion}
          region={this.state.region}
          onRegionChange={() => this.onRegionChange()}
        >
          {this.state.marker1 &&
            <MapView.Marker
              coordinate={this.state.marker1}
              pinColor="#27ae60"
              title='Start Trip'
              description={this.state.desc}
            />   
          }
          {this.state.marker2 &&
            <MapView.Marker
              coordinate={this.state.marker2}
              pinColor="#2980b9"
              title='Finish Trip'
              description={this.state.desc2}
            /> 
          }

          <MapView.Polyline
              key="editingPolyline"
              coordinates={this.state.coordinates}
              strokeColor="#d35400"
              fillColor="rgba(255,0,0,0.5)"
              strokeWidth={2}
              lineCap="square"
          />

           {titikTrip}

        </MapView>
        <Spinner overlayColor={global.overlayColor} visible={this.state.showLoader} textContent={this.state.textLoader} textStyle={{color: '#FFF'}} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  customView: {
    width: 140,
    height: 100,
  },
  plainView: {
    width: 60,
  },
  container: {
    flex:1,
    backgroundColor: '#ffffff'
  },
  map: {
    // width:'100%',
    // height:'100%'
    flex:1
  },
  bubble: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.7)',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 20,
  },
  latlng: {
    width: 200,
    alignItems: 'stretch',
  },
  button: {
    width: 80,
    paddingHorizontal: 12,
    alignItems: 'center',
    marginHorizontal: 10,
  },
  buttonContainer: {
    flexDirection: 'row',
    marginVertical: 20,
    backgroundColor: 'transparent',
  },
});

module.exports = LocationPolyline;

```

### LINKED ISSUE #1776: animateToBearing, animateToViewingAngle not working for Google Maps + expo + iOS only
Hey all,

I have a similar issue to #1743 but I have isolated it to Google Maps + expo + iOS only. I get this error using the [(example code)](https://github.com/airbnb/react-native-maps/blob/master/example/examples/DisplayLatLng.js) for animateToBearing and animateToViewingAngle for Google Maps + expo + iOS:

`undefined is not an object (evaluating 'this._mapManagerCommand(name).apply')`

The same project and test code is working correctly with:

- Google Maps + expo + android
- iOS native maps + expo + iOS 
- Google Maps + non-expo project + android

for these three both animateToBearing and animateToViewingAngle are working flawlessly! 

So it seems the issue is isolated to Google Maps + expo + iOS.

I am really hoping to have Google Maps + expo + iOS working in a project specifically to use Google's terrain view. Any help or insight would be greatly appreciated!

### LINKED ISSUE #1793: onMapReady being called whenever a tile is rendered, which tries to reset everything to props
So it consumes too much resources by resetting everything, moving to the initialRegion and refreshing the style, and not allowing to actually change the region by dragging!

### PR DESCRIPTION
**Pull request by danielgindi**
(Closes #1793)

Also: Closes #1776, Closes #1696, Closes #1680, Closes #1605)
Probably closes more issues related to iOS, panning and scrolling.

---

The issue is that on Android, the onMapReady comes from the native onMapReady event, which occurs when Google Play Services first provides a Google Maps view.

But on iOS - it happened whenever rendering has finished - which is a completely different interpretation, and misses the point of just doing the initial stuff like `initialRegion`/`region`.

### CODE REVIEW

File: lib/ios/AirMaps/AIRMapManager.m [hunk 1]
```diff
@@ -716,9 +725,6 @@ - (void)mapViewWillStartRenderingMap:(AIRMap *)mapView
 - (void)mapViewDidFinishRenderingMap:(AIRMap *)mapView fullyRendered:(BOOL)fullyRendered
 {
     [mapView finishLoading];
-    [mapView cacheViewIfNeeded];
```
Comment (danielgindi) [inline lib/ios/AirMaps/AIRMapManager.m]: This was also an issue: `cacheViewIfNeeded` is called on `finishLoading` also, which is a tremendous overhead that is not necessary.
As caching an image is a CPU and RAM consuming job.

Comment (IjzerenHein) [reply lib/ios/AirMaps/AIRMapManager.m]: Hi, I'm sorry to say but this commit is quite flawed. It creates a global variable called `didCallOnMapReady` which once set to YES is never reset to NO. This breaks `onMapReady` quite badly, causing it now to only fire on the first rendered MapView and after that never again (not when MapView is unmounted/mounted, or for any other MapViews).

@danielgindi @christopherdro

Comment (IjzerenHein) [reply lib/ios/AirMaps/AIRMapManager.m]: Fixed by PR #1853
